import { describe, expect, it } from 'vitest'

describe('Sidebar user entry UI', () => {
  it('keeps auth modal and user menu as external components used by Sidebar', async () => {
    const fs = process.getBuiltinModule('fs/promises')
    const sidebar = await fs.readFile(new URL('../../components/Sidebar.vue', import.meta.url), 'utf-8')

    expect(sidebar).toContain('isMockLoggedIn')
    expect(sidebar).toContain('mockUsername')
    expect(sidebar).toContain("import AuthModal from './auth/AuthModal.vue'")
    expect(sidebar).toContain("import UserMenu from './auth/UserMenu.vue'")
    expect(sidebar).toContain('<AuthModal')
    expect(sidebar).toContain('<UserMenu')
    expect(sidebar).toContain(':isLoggedIn="isMockLoggedIn"')
    expect(sidebar).toContain('@login="openAuthModal(\'login\')"')
    expect(sidebar).toContain('@register="openAuthModal(\'register\')"')
    expect(sidebar).toContain('@logout="handleLogout"')
    expect(sidebar).toContain(':initialMode="authModalMode"')
    expect(sidebar).not.toContain('邮箱登录')
    expect(sidebar).not.toContain('使用 GitHub 账号登录')
    expect(sidebar).not.toContain('检查更新')
  })

  it('keeps auth modal presentation in AuthModal.vue', async () => {
    const fs = process.getBuiltinModule('fs/promises')
    const authModal = await fs.readFile(new URL('../../components/auth/AuthModal.vue', import.meta.url), 'utf-8')

    expect(authModal).toContain('登录')
    expect(authModal).toContain('注册')
    expect(authModal).toContain('邮箱登录')
    expect(authModal).toContain('验证码登录')
    expect(authModal).toContain('邮箱注册')
    expect(authModal).toContain('验证码注册')
    expect(authModal).toContain('使用 GitHub 账号登录')
    expect(authModal).toContain('使用 GitHub 账号注册')
    expect(authModal).toContain("defineProps<{")
    expect(authModal).toContain('open: boolean')
    expect(authModal).toContain("initialMode?: 'login' | 'register'")
    expect(authModal).toContain('watch(')
    expect(authModal).toContain("defineEmits<{")
    expect(authModal).toContain("(e: 'close'): void")
  })

  it('keeps logged-out and logged-in user menu presentation in UserMenu.vue', async () => {
    const fs = process.getBuiltinModule('fs/promises')
    const userMenu = await fs.readFile(new URL('../../components/auth/UserMenu.vue', import.meta.url), 'utf-8')

    expect(userMenu).toContain('isLoggedIn: boolean')
    expect(userMenu).toContain('username: string')
    expect(userMenu).toContain('登录')
    expect(userMenu).toContain('注册')
    expect(userMenu).toContain('退出登录')
    expect(userMenu).toContain('检查更新')
    expect(userMenu).toContain('帮助文档')
    expect(userMenu).toContain('联系我们')
    expect(userMenu).toContain('报告问题')
    expect(userMenu).toContain("defineEmits<{")
    expect(userMenu).toContain("(e: 'close'): void")
    expect(userMenu).toContain("(e: 'login'): void")
    expect(userMenu).toContain("(e: 'register'): void")
    expect(userMenu).toContain("(e: 'logout'): void")
  })
})
